
### Sign up a user 
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"abdellatif@gmail.com",
    "password":"23038"
}

### Sign in a user 
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"abdellatif@gmail.com",
    "password":"23038"
}


### Find a user by ID : 
GET http://localhost:3000/auth/1


### find by email
GET http://localhost:3000/auth?email=tijani.idrissi.abdellatif@gmail.com

### Delete a user 
DELETE  http://localhost:3000/auth/2


### update a user 
PATCH http://localhost:3000/auth/1
Content-Type: application/json

{
    "email":"tijani.idrissi.abdellatif@gmail.com",
    "password":"fortyfour"
}


### Set a color 
GET http://localhost:3000/auth/colors/red 


### Get the color 
GET http://localhost:3000/auth/colors


### Who ami  get the current signed in user
GET http://localhost:3000/auth/whoami


### Sign out the current signed user 
POST http://localhost:3000/auth/signout